sync_mod_dir = [

] # 要同步的模组目录列表 以sync_minecraft_dir为根目录
sync_minecraft_dir = "" # Minecraft的根目录路径（versions/<版本>/） 使用绝对路径 
chunk_size = 1048576  # 每次传输的文件块大小，单位为字节 (默认1MB)（现在没什么用）

ip = "" # 服务器IP地址
port = 0 # 服务器端口号